amp: true
batch: 16
box: 7.5
cache: false
close_mosaic: 10
cls: 0.5
copy_paste: 0.0
cos_lr: true
data: c:\Users\Hp\Desktop\traffic\traffic_dataset\dataset.yaml
degrees: 0.0
deterministic: true
device: cpu
dfl: 1.5
epochs: 50
exist_ok: true
fliplr: 0.5
flipud: 0.0
fraction: 1.0
freeze: null
hsv_h: 0.015
hsv_s: 0.7
hsv_v: 0.4
imgsz: 640
kobj: 1.0
label_smoothing: 0.0
lr0: 0.01
lrf: 0.01
mixup: 0.0
mode: train
model: yolov8n.pt
momentum: 0.937
mosaic: 1.0
name: traffic_yolo_20250906_111257
nbs: 64
optimizer: SGD
patience: 20
perspective: 0.0
pose: 12.0
pretrained: true
profile: false
project: c:\Users\Hp\Desktop\traffic\runs
rect: false
resume: false
save: true
save_period: 10
scale: 0.5
seed: 42
shear: 0.0
single_cls: false
task: detect
translate: 0.1
verbose: true
warmup_bias_lr: 0.1
warmup_epochs: 3.0
warmup_momentum: 0.8
weight_decay: 0.0005
workers: 4
